app.services.greeting.message: Hello World

spring:
  datasource:
    username: ${POSTGRESQL_USER:postgres}
    password: ${POSTGRESQL_PASSWORD:123}
    url: jdbc:postgresql://${POSTGRESQL_SERVICE_HOST:localhost}:${POSTGRESQL_SERVICE_PORT:5432}/${POSTGRESQL_DATABASE:test}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    show-sql : true
    hibernate:
      ddl-auto : update
  main:
    allow-bean-definition-overriding: true

  # V(version)__description.sql
#  flyway:
#    baseline-on-migrate: true

